import { lazy, Suspense, useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Bot, Box, Check, ChevronDown, Download, Eye, FileDown, Filter, Globe2, Headphones, Languages, MessageCircleMore, PackagePlus, Plus, RotateCcw, Search, Send, ShoppingCart, SlidersHorizontal, Sparkles, Star, Trash2, WandSparkles, WifiOff } from 'lucide-react'
import { client, safeGet, safePost } from '../api/client'
import { Badge, Card, DemoNotice, Disclaimer, MetricCard, PageHeader, ProductVisual, ProgressBar, ScoreRing, toneForRisk } from '../components/ui'
import { customers as fallbackCustomers, inquiries as fallbackInquiries, products as fallbackProducts, scenarios as fallbackScenarios } from '../data/fallback'
import type { Customer, Inquiry, Product } from '../types'

const ShowroomCanvas = lazy(() => import('../components/Showroom3D').then(module => ({ default: module.ShowroomCanvas })))

export function ProductPage() {
  const [items, setItems] = useState<Product[]>(fallbackProducts)
  const [tab, setTab] = useState<'list' | 'design'>('design')
  const [category, setCategory] = useState('保温杯')
  const [country, setCountry] = useState('法国')
  const [color, setColor] = useState('海盐蓝')
  const [style, setStyle] = useState('现代简约')
  const [loading, setLoading] = useState(false)
  const [concept, setConcept] = useState<any>(null)
  const [selected, setSelected] = useState<Product | null>(null)
  useEffect(() => { safeGet('/products', fallbackProducts).then(result => setItems(result.data as Product[])) }, [])
  const generate = async () => {
    setLoading(true); setConcept(null)
    const fallback = { name: `${color} · EcoPulse ${category}`, positioning: `面向${country}年轻家庭的高性价比可持续生活产品`, concept: `以${style}为核心，将义乌柔性供应链与城市通勤场景结合。`, palette: [color, '云雾白', '深海蓝'], packaging: 'FSC纸浆一体包装，可选中法双语与欧盟标签', selling_points: ['环保材料可追溯', '小批量快速定制', '支持多语言包装', '模块化可替换配件'], suggested_price: '12-18 USD', target_market: country, market_match_score: 92, estimated_margin_rate: 36, estimated_lead_days: 21, image_variant: (category.length + country.length) % 5, provider: 'MockAIProvider', process: ['解析目标市场', '匹配调研洞察', '生成设计语言', '评估供应链可行性'] }
    const result = await safePost('/products/generate', { category, target_country: country, target_customer: '18-35岁城市消费者', style, color, price_range: '12-18 USD', usage: '通勤与户外', requirements: '环保、可定制、适合礼赠' }, fallback)
    setTimeout(() => { setConcept(result.data); setLoading(false) }, 700)
  }
  return <div>
    <PageHeader eyebrow="PRODUCT INTELLIGENCE" title="产品管理与AI设计中心" description="把市场趋势、客户画像和义乌柔性供应链，变成可落地的产品方案。" actions={<div className="segmented"><button className={tab === 'design' ? 'active' : ''} onClick={() => setTab('design')}>AI产品设计</button><button className={tab === 'list' ? 'active' : ''} onClick={() => setTab('list')}>产品库 {items.length}</button></div>} />
    {tab === 'design' ? <div className="product-design-layout">
      <Card className="design-form" title={<><WandSparkles size={18} />输入市场机会</>}>
        <label>产品类别<input value={category} onChange={e => setCategory(e.target.value)} /></label>
        <div className="form-row"><label>目标国家<select value={country} onChange={e => setCountry(e.target.value)}><option>法国</option><option>美国</option><option>西班牙</option><option>阿联酋</option></select></label><label>目标客户<select><option>18-35岁城市消费者</option><option>家庭采购者</option><option>企业礼赠</option></select></label></div>
        <div className="form-row"><label>风格偏好<select value={style} onChange={e => setStyle(e.target.value)}><option>现代简约</option><option>自然环保</option><option>潮流多彩</option><option>轻奢商务</option></select></label><label>主要颜色<input value={color} onChange={e => setColor(e.target.value)} /></label></div>
        <div className="form-row"><label>价格区间<select><option>12-18 USD</option><option>8-12 USD</option><option>18-30 USD</option></select></label><label>使用场景<select><option>通勤与户外</option><option>家庭日用</option><option>节日礼赠</option></select></label></div>
        <label>自定义需求<textarea defaultValue="环保材料、支持Logo定制、适合跨境电商运输与法语包装" /></label>
        <button className="btn btn-primary btn-block" onClick={generate} disabled={loading}><Sparkles size={17} />{loading ? 'AI 正在生成产品方案…' : '生成产品方案'}</button>
        <DemoNotice>默认使用预置规则和高质量本地方案，无需外部API。</DemoNotice>
      </Card>
      <Card className="concept-panel">
        {loading ? <div className="ai-process"><div className="ai-loader"><Sparkles size={28} /></div><h3>正在把市场需求变成产品</h3>{['解析目标市场', '匹配调研洞察', '生成设计语言', '评估供应链可行性'].map((step, index) => <div key={step} className="process-step"><span className={index < 3 ? 'done' : 'active'}>{index < 3 ? <Check size={13} /> : index + 1}</span>{step}</div>)}</div> : concept ? <div className="concept-result">
          <div className="concept-hero"><ProductVisual variant={concept.image_variant} /><div className="concept-overlay"><Badge tone="success">MARKET MATCH {concept.market_match_score}</Badge><span>AI生成式产品概念图 · Mock</span></div></div>
          <div className="concept-title"><div><span>AI CONCEPT 01</span><h2>{concept.name}</h2><p>{concept.positioning}</p></div><ScoreRing value={concept.market_match_score} label="市场匹配" tone="green" /></div>
          <div className="concept-grid"><div><span>设计理念</span><p>{concept.concept}</p></div><div><span>包装建议</span><p>{concept.packaging}</p></div></div>
          <div className="palette-row"><span>配色方案</span>{concept.palette.map((item: string, index: number) => <i key={item} style={{ background: ['#5b8cff', '#ecf4f8', '#102e50'][index] }} title={item} />)}<strong>{concept.palette.join(' · ')}</strong></div>
          <div className="selling-points">{concept.selling_points.map((item: string) => <span key={item}><Check size={14} />{item}</span>)}</div>
          <div className="concept-metrics"><MetricCard label="建议售价" value={concept.suggested_price} tone="blue" /><MetricCard label="预计毛利率" value={concept.estimated_margin_rate} suffix="%" tone="green" /><MetricCard label="预计交货周期" value={concept.estimated_lead_days} suffix="天" tone="violet" /></div>
          <div className="button-row"><button className="btn btn-secondary"><RotateCcw size={15} />重新生成</button><button className="btn btn-primary"><PackagePlus size={15} />保存到产品库</button></div>
        </div> : <div className="concept-empty"><div className="empty-orbit"><WandSparkles size={34} /></div><h3>等待生成你的下一款全球商品</h3><p>填写左侧目标市场与产品要求，AI将生成完整的产品定位、视觉概念和量化预测。</p><div className="template-row"><button onClick={() => { setCategory('环保保温杯'); setCountry('法国') }}>法国 · 环保杯</button><button onClick={() => { setCategory('太阳能灯'); setCountry('南非') }}>南非 · 太阳能灯</button><button onClick={() => { setCategory('旅行收纳'); setCountry('美国') }}>美国 · 旅行收纳</button></div></div>}
      </Card>
    </div> : <><div className="toolbar"><div className="searchbox"><Search size={16} /><input placeholder="搜索产品名称、SKU或标签" /></div><select><option>全部分类</option><option>家居日用</option><option>箱包</option><option>户外用品</option></select><button className="btn btn-primary"><Plus size={15} />新建产品</button></div><div className="product-grid">{items.map((product, index) => <Card key={product.id} className="product-card"><button className="product-open" onClick={() => setSelected(product)}><ProductVisual variant={index} /><div className="product-info"><div><Badge tone={index === 0 ? 'success' : 'blue'}>{product.category}</Badge><span className="heat"><Star size={13} />{product.popularity}</span></div><h3>{product.name}</h3><p>{product.description}</p><div className="product-stats"><span><small>FOB参考价</small><strong>${product.price}</strong></span><span><small>MOQ</small><strong>{product.moq}</strong></span><span><small>交期</small><strong>{product.lead_days}天</strong></span></div></div></button></Card>)}</div></>}
    {selected && <div className="drawer-scrim" onClick={() => setSelected(null)}><aside className="detail-drawer" onClick={e => e.stopPropagation()}><button className="drawer-close" onClick={() => setSelected(null)}>×</button><ProductVisual variant={selected.id - 1} /><Badge tone="blue">{selected.category}</Badge><h2>{selected.name}</h2><p>{selected.description}</p><div className="detail-list"><span>SKU <b>{selected.sku}</b></span><span>参考价 <b>${selected.price}</b></span><span>成本 <b>${selected.cost}</b></span><span>MOQ <b>{selected.moq}件</b></span><span>库存 <b>{selected.stock.toLocaleString()}件</b></span><span>目标市场 <b>{selected.target_markets}</b></span></div><button className="btn btn-primary btn-block">编辑产品信息</button></aside></div>}
  </div>
}

export function ShowroomPage({ role }: { role: 'merchant' | 'buyer' }) {
  const [items, setItems] = useState<Product[]>(fallbackProducts)
  const [selected, setSelected] = useState(0)
  const [theme, setTheme] = useState('tech')
  const [language, setLanguage] = useState('EN')
  const [force2D, setForce2D] = useState(false)
  const [cart, setCart] = useState<number[]>([])
  const [narrating, setNarrating] = useState(false)
  useEffect(() => { safeGet('/products', fallbackProducts).then(result => setItems(result.data as Product[])) }, [])
  const product = items[selected] || fallbackProducts[0]
  const add = () => setCart(existing => existing.includes(product.id) ? existing : [...existing, product.id])
  return <div className="showroom-page">
    <PageHeader eyebrow="IMMERSIVE DIGITAL SHOWROOM" title="3D数字展台" description={role === 'buyer' ? '沉浸式浏览义乌好货，AI随时为你讲解。' : '用可交互空间向全球采购商展示产品与信用。'} actions={<><Badge tone="success">商户信用 92 / 100</Badge><button className="btn btn-secondary" onClick={() => setForce2D(value => !value)}>{force2D ? <Box size={16} /> : <WifiOff size={16} />}{force2D ? '切换3D' : '2D降级演示'}</button></>} />
    <div className="showroom-toolbar"><div><span>展台主题</span><div className="theme-dots"><button className={theme === 'tech' ? 'active tech' : 'tech'} onClick={() => setTheme('tech')} /><button className={theme === 'jade' ? 'active jade' : 'jade'} onClick={() => setTheme('jade')} /><button className={theme === 'warm' ? 'active warm' : 'warm'} onClick={() => setTheme('warm')} /></div></div><div><Languages size={15} /><select value={language} onChange={e => setLanguage(e.target.value)}><option>EN</option><option>中文</option><option>FR</option><option>ES</option><option>AR</option><option>RU</option></select></div><span className="showroom-live"><span />5 products online</span><button className="cart-pill"><ShoppingCart size={16} />询盘单 {cart.length}</button></div>
    <div className="showroom-layout"><div className="showroom-stage"><Suspense fallback={<div className="scene-loading"><LoaderScene /></div>}><ShowroomCanvas products={items} selected={selected} onSelect={setSelected} theme={theme} force2D={force2D} /></Suspense></div><aside className="showroom-detail"><div className="detail-top"><Badge tone="danger">HOT · {product.popularity}</Badge><span>{language}</span></div><div className="mini-product"><ProductVisual variant={selected} compact /></div><span className="sku">{product.sku}</span><h2>{product.name}</h2><p>{product.multilingual_points}</p><div className="showroom-price"><strong>${product.price.toFixed(2)}</strong><span>FOB Ningbo</span></div><div className="spec-grid"><span><small>MOQ</small><b>{product.moq} pcs</b></span><span><small>Lead time</small><b>{product.lead_days} days</b></span><span><small>Stock</small><b>{product.stock.toLocaleString()}</b></span><span><small>Markets</small><b>{product.target_markets.split(',')[0]}</b></span></div><div className="feature-list">{product.tags.split(',').map(tag => <span key={tag}><Check size={14} />{tag}</span>)}</div><button className="btn btn-secondary btn-block" onClick={() => { setNarrating(true); setTimeout(() => setNarrating(false), 2200) }}><Headphones size={16} />{narrating ? 'AI正在讲解这款商品…' : 'AI讲解'}</button><button className="btn btn-primary btn-block" onClick={add}><ShoppingCart size={16} />{cart.includes(product.id) ? '已加入询盘单' : '添加到询盘单'}</button><div className="merchant-trust"><div><ShieldCheckIcon /><span><strong>义乌优选商户</strong><small>资料完整 · 18笔历史订单</small></span></div><b>92</b></div></aside></div>
  </div>
}

function ShieldCheckIcon() { return <div className="shield-mini"><Check size={14} /></div> }
function LoaderScene() { return <><Box size={32} /><span>正在加载3D数字展台…</span></> }

type Message = { role: string; content: string }

export function AssistantPage() {
  const navigate = useNavigate()
  const [scenarioList, setScenarioList] = useState<any[]>(fallbackScenarios)
  const [messages, setMessages] = useState<Message[]>([{ role: 'assistant', content: '您好！我是您的义乌AI多语言销售助手。我可以推荐商品、说明MOQ与交期，或立即生成报价。' }])
  const [input, setInput] = useState('')
  const [language, setLanguage] = useState('中文')
  const [typing, setTyping] = useState(false)
  const [insight, setInsight] = useState<any>({ intent_score: 64, estimated_order_amount: 15360, concerns: ['产品匹配', '价格'], stage: '需求澄清', risk_score: 18, risk_tip: '当前未发现显著异常', next_action: '继续澄清需求', recommended_reply: '请确认采购数量、目的港和期望交期。' })
  const [activeScenario, setActiveScenario] = useState<string | null>(null)
  const bottom = useRef<HTMLDivElement>(null)
  useEffect(() => { safeGet('/demo/scenarios', fallbackScenarios).then(result => setScenarioList(result.data as any[])) }, [])
  useEffect(() => { bottom.current?.scrollIntoView({ behavior: 'smooth' }) }, [messages, typing])
  const mockReply = (text: string, scenario?: string) => {
    const lower = text.toLowerCase()
    if (scenario === 'C' || /cod|货到付款|refuse|不提供/.test(lower)) return { reply: '为保障双方交易安全，大额首单需完成公司信息核验，并采用100%预付款或不可撤销信用证。我们暂不接受无身份资料的货到付款。', intent_score: 61, estimated_order_amount: 384000, concerns: ['付款方式', '身份验证', '账户安全'], stage: '风险核验', risk_score: 88, risk_tip: '建议暂停自动报价并核验企业身份', next_action: '身份核验', recommended_reply: '请提供公司注册文件并安排视频核验。' }
    if (/discount|lower|降价|便宜/.test(lower)) return { reply: '可以按数量提供阶梯价格：1,000件为 $12.80，3,000件可至 $11.90。若采用标准包装，还可再优化约2%。您希望先看正式报价吗？', intent_score: 86, estimated_order_amount: 59500, concerns: ['阶梯价格', '包装成本', '交期'], stage: '议价', risk_score: 28, risk_tip: '订单量增长较快，建议确认采购授权', next_action: '生成阶梯报价', recommended_reply: '我可以为5,000件方案保留7天价格。' }
    if (/eco|环保|bpa|french/.test(lower)) return { reply: '推荐 EcoPulse 环保保温杯：食品级304不锈钢、BPA-free杯盖与FSC包装，MOQ 500件，常规交期18天，也支持法语包装。', intent_score: 82, estimated_order_amount: 25600, concerns: ['环保认证', '材料', '法语包装'], stage: '产品匹配', risk_score: 14, risk_tip: '当前未发现显著异常', next_action: '生成阶梯报价', recommended_reply: '是否需要先寄送2件样品确认颜色和包装？' }
    return { reply: '我已记录您的需求。请继续确认数量、目的港和目标价格，我会匹配最合适的义乌商品并生成报价。', intent_score: 72, estimated_order_amount: 18000, concerns: ['数量', '价格', '交期'], stage: '需求澄清', risk_score: 18, risk_tip: '当前未发现显著异常', next_action: '继续澄清需求', recommended_reply: '请告知目的港和预计下单时间。' }
  }
  const send = async (preset?: string) => {
    const text = preset || input.trim(); if (!text) return
    setMessages(existing => [...existing, { role: 'user', content: text }]); setInput(''); setTyping(true)
    const fallback = mockReply(text, activeScenario || undefined)
    const result = await safePost('/ai/chat', { message: text, language, scenario: activeScenario, history: messages.slice(-10) }, fallback)
    setTimeout(() => { setInsight(result.data); setMessages(existing => [...existing, { role: 'assistant', content: result.data.reply }]); setTyping(false) }, 500)
  }
  const loadScenario = (scenario: any) => { setActiveScenario(scenario.code); setLanguage(scenario.code === 'A' ? 'Français' : 'English'); setMessages(scenario.messages); const prompt = scenario.messages.find((m: Message) => m.role === 'user')?.content || ''; setInsight(mockReply(prompt, scenario.code)) }
  return <div>
    <PageHeader eyebrow="MULTILINGUAL SALES AGENT" title="AI多语言销售助手" description="会推荐、会报价、会谈判，也会在风险出现时及时踩下刹车。" actions={<select className="language-select" value={language} onChange={e => setLanguage(e.target.value)}><option>中文</option><option>English</option><option>Español</option><option>Français</option><option>Русский</option><option>العربية</option></select>} />
    <div className="assistant-layout">
      <aside className="scenario-panel"><h3><Sparkles size={17} />路演场景</h3>{scenarioList.map(scenario => <button key={scenario.code} className={activeScenario === scenario.code ? 'active' : ''} onClick={() => loadScenario(scenario)}><span>{scenario.code}</span><div><strong>{scenario.title}</strong><small>{scenario.description}</small></div><Badge tone={toneForRisk(scenario.risk_hint)}>{scenario.risk_hint}</Badge></button>)}<div className="assistant-help"><Bot size={20} /><strong>Mock AI 已就绪</strong><span>关键词规则会根据价格、交期、环保和付款条件生成不同回复。</span></div></aside>
      <Card className="chat-panel"><div className="chat-head"><div className="avatar"><Bot size={21} /></div><div><strong>Yiwu AI Sales</strong><span><i />在线 · {language}</span></div><Badge tone="success">平均响应 8秒</Badge></div><div className="messages">{messages.map((message, index) => <div key={index} className={`message ${message.role}`}><span className="message-avatar">{message.role === 'assistant' ? <Bot size={17} /> : <Globe2 size={17} />}</span><div><p>{message.content}</p><small>{message.role === 'assistant' ? 'AI Sales · just now' : 'Buyer · just now'}</small></div></div>)}{typing && <div className="message assistant"><span className="message-avatar"><Bot size={17} /></span><div className="typing"><i /><i /><i /></div></div>}<div ref={bottom} /></div><div className="quick-prompts"><button onClick={() => send('这款产品的MOQ是多少？')}>询问MOQ</button><button onClick={() => send('5,000件可以降价吗？')}>模拟议价</button><button onClick={() => send('请为我生成正式报价')}>获取报价</button></div><div className="chat-input"><textarea value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); send() } }} placeholder="输入采购需求，例如：需要2,000个环保保温杯…" /><button onClick={() => send()} disabled={typing}><Send size={18} /></button></div></Card>
      <aside className="insight-panel"><div className="insight-title"><Sparkles size={17} /><div><strong>AI实时洞察</strong><span>随对话动态更新</span></div></div><div className="insight-scores"><ScoreRing value={insight.intent_score} label="购买意向" tone="green" /><ScoreRing value={insight.risk_score} label="风险分" tone={insight.risk_score >= 60 ? 'red' : 'blue'} /></div><div className="insight-amount"><span>预计订单金额</span><strong>${Number(insight.estimated_order_amount || 0).toLocaleString()}</strong></div><div className="insight-block"><span>客户关注点</span><div className="tag-row">{(insight.concerns || []).map((item: string) => <Badge key={item} tone="blue">{item}</Badge>)}</div></div><div className="insight-grid"><span>谈判阶段 <b>{insight.stage}</b></span><span>下一步行动 <b>{insight.next_action}</b></span></div><div className={`risk-tip ${insight.risk_score >= 60 ? 'danger' : ''}`}><strong>{insight.risk_score >= 60 ? '⚠ 潜在风险' : '✓ 风险提示'}</strong><span>{insight.risk_tip}</span></div><div className="reply-suggestion"><strong>推荐回复</strong><p>{insight.recommended_reply}</p><button onClick={() => setInput(insight.recommended_reply)}>填入输入框</button></div><button className="btn btn-primary btn-block" onClick={() => navigate('/crm')}><FileDown size={16} />生成询盘摘要</button></aside>
    </div>
  </div>
}

export function CrmPage() {
  const [tab, setTab] = useState<'inquiries' | 'customers'>('inquiries')
  const [inquiryItems, setInquiryItems] = useState<Inquiry[]>(fallbackInquiries)
  const [customerItems, setCustomerItems] = useState<Customer[]>(fallbackCustomers)
  const [query, setQuery] = useState('')
  const [riskFilter, setRiskFilter] = useState('全部风险')
  const [selected, setSelected] = useState<Inquiry | Customer | null>(null)
  const navigate = useNavigate()
  useEffect(() => { safeGet('/inquiries', fallbackInquiries).then(result => setInquiryItems(result.data as Inquiry[])); safeGet('/customers', fallbackCustomers).then(result => setCustomerItems(result.data as Customer[])) }, [])
  const filteredInquiries = useMemo(() => inquiryItems.filter(item => (item.customer + item.product + item.inquiry_no).toLowerCase().includes(query.toLowerCase()) && (riskFilter === '全部风险' || (riskFilter === '高风险' ? item.risk_score >= 60 : item.risk_score < 30))), [inquiryItems, query, riskFilter])
  const filteredCustomers = useMemo(() => customerItems.filter(item => (item.company + item.contact + item.country).toLowerCase().includes(query.toLowerCase())), [customerItems, query])
  const updateStatus = async (item: Inquiry, status: string) => { setInquiryItems(list => list.map(row => row.id === item.id ? { ...row, status } : row)); await client.patch(`/inquiries/${item.id}`, { status }).catch(() => undefined) }
  return <div>
    <PageHeader eyebrow="SMART CRM" title="智能询盘与客户管理" description="让每一条询盘都有摘要、意向判断、风险标记和明确下一步。" actions={<button className="btn btn-primary"><Plus size={15} />新建询盘</button>} />
    <div className="crm-summary"><MetricCard label="全部客户" value={customerItems.length} change="覆盖5个国家" tone="blue" /><MetricCard label="活跃询盘" value={inquiryItems.length} change="今日新增2条" tone="cyan" /><MetricCard label="高意向" value={inquiryItems.filter(i => i.intent_score >= 80).length} change="建议优先跟进" tone="green" /><MetricCard label="高风险待复核" value={inquiryItems.filter(i => i.risk_score >= 60).length} change="其中1条已拦截" tone="red" /></div>
    <Card className="crm-card"><div className="crm-tabs"><button className={tab === 'inquiries' ? 'active' : ''} onClick={() => setTab('inquiries')}>询盘列表 <span>{inquiryItems.length}</span></button><button className={tab === 'customers' ? 'active' : ''} onClick={() => setTab('customers')}>客户列表 <span>{customerItems.length}</span></button></div><div className="toolbar"><div className="searchbox"><Search size={16} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="搜索编号、客户、产品或国家" /></div><select value={riskFilter} onChange={e => setRiskFilter(e.target.value)}><option>全部风险</option><option>低风险</option><option>高风险</option></select><button className="btn btn-secondary"><SlidersHorizontal size={15} />更多筛选</button></div>
      {tab === 'inquiries' ? <div className="table-wrap"><table><thead><tr><th>询盘 / 客户</th><th>产品与数量</th><th>目标价</th><th>意向</th><th>风险</th><th>状态</th><th>推荐行动</th><th /></tr></thead><tbody>{filteredInquiries.map(item => <tr key={item.id}><td><button className="link-cell" onClick={() => setSelected(item)}><strong>{item.inquiry_no}</strong><span>{item.country} · {item.customer}</span></button></td><td><strong>{item.product}</strong><span>{item.quantity.toLocaleString()}件</span></td><td>${item.target_price.toFixed(2)}</td><td><div className="score-cell"><ProgressBar value={item.intent_score} tone="green" /><b>{item.intent_score}</b></div></td><td><Badge tone={toneForRisk(item.risk_score)}>{item.risk_score} · {item.risk_score >= 80 ? '极高' : item.risk_score >= 60 ? '高' : item.risk_score >= 30 ? '中' : '低'}</Badge></td><td><select className="status-select" value={item.status} onChange={e => updateStatus(item, e.target.value)}><option>待处理</option><option>跟进中</option><option>已报价</option><option>风险复核</option><option>已拦截</option><option>已转订单</option></select></td><td className="action-cell">{item.recommended_action}</td><td><button className="icon-btn" onClick={() => setSelected(item)}><Eye size={16} /></button></td></tr>)}</tbody></table></div> : <div className="table-wrap"><table><thead><tr><th>公司 / 联系人</th><th>国家</th><th>来源</th><th>历史订单</th><th>成交金额</th><th>意向</th><th>信用 / 风险</th><th>最近联系</th></tr></thead><tbody>{filteredCustomers.map(item => <tr key={item.id} onClick={() => setSelected(item)}><td><strong>{item.company}</strong><span>{item.contact} · {item.email}</span></td><td>{item.country}</td><td>{item.source}</td><td>{item.historical_orders}笔</td><td>${item.historical_amount.toLocaleString()}</td><td><Badge tone={item.intent_level === '高' ? 'success' : 'blue'}>{item.intent_level}意向</Badge></td><td><b className="credit-score">{item.credit_score}</b> <Badge tone={toneForRisk(item.risk_level)}>{item.risk_level}</Badge></td><td>{item.last_contact}</td></tr>)}</tbody></table></div>}
    </Card>
    {selected && <div className="drawer-scrim" onClick={() => setSelected(null)}><aside className="detail-drawer wide" onClick={e => e.stopPropagation()}><button className="drawer-close" onClick={() => setSelected(null)}>×</button>{'inquiry_no' in selected ? <><Badge tone={toneForRisk(selected.risk_score)}>风险分 {selected.risk_score}</Badge><h2>{selected.inquiry_no}</h2><p>{selected.customer} · {selected.country}</p><div className="ai-summary"><Sparkles size={18} /><div><strong>AI询盘总结</strong><p>{selected.ai_summary}</p></div></div><div className="detail-list"><span>产品 <b>{selected.product}</b></span><span>数量 <b>{selected.quantity.toLocaleString()}件</b></span><span>目标价 <b>${selected.target_price}</b></span><span>付款方式 <b>{selected.payment_method}</b></span><span>交付地点 <b>{selected.destination}</b></span><span>期望交期 <b>{selected.expected_delivery}</b></span></div><div className="recommend-box"><strong>推荐行动</strong><p>{selected.recommended_action}</p></div><div className="drawer-actions"><button className="btn btn-secondary" onClick={() => navigate('/risk')}>查看风险</button><button className="btn btn-primary" onClick={() => navigate('/quotes')}>转换为报价</button></div></> : <><Badge tone={toneForRisk(selected.risk_level)}>{selected.risk_level}</Badge><h2>{selected.company}</h2><p>{selected.country} · {selected.contact}</p><ScoreRing value={selected.credit_score} label="信用评分" tone={selected.credit_score >= 80 ? 'green' : 'blue'} /><div className="detail-list"><span>企业邮箱 <b>{selected.email}</b></span><span>注册年限 <b>{selected.registered_years}年</b></span><span>历史订单 <b>{selected.historical_orders}笔</b></span><span>历史成交 <b>${selected.historical_amount.toLocaleString()}</b></span><span>客户来源 <b>{selected.source}</b></span><span>标签 <b>{selected.tags}</b></span></div><button className="btn btn-primary btn-block" onClick={() => navigate('/risk')}>打开数字信任档案</button></>}</aside></div>}
  </div>
}

export function QuotePage() {
  const [form, setForm] = useState({ product_id: 1, quantity: 2200, unit_price: 12.8, unit_cost: 7.6, discount: 3, packaging_fee: 180, freight: 980, insurance: 60, tax_rate: 2, incoterm: 'FOB' })
  const [result, setResult] = useState<any>(null)
  const [saved, setSaved] = useState<any>(null)
  const [downloading, setDownloading] = useState(false)
  const product = fallbackProducts.find(item => item.id === Number(form.product_id)) || fallbackProducts[0]
  const localCalculate = () => { const subtotal = form.unit_price * form.quantity; const discounted = subtotal * (1 - form.discount / 100); const tax = discounted * form.tax_rate / 100; const total = discounted + form.packaging_fee + form.freight + form.insurance + tax; const cost = form.unit_cost * form.quantity + form.packaging_fee + form.freight + form.insurance; const profit = total - cost; return { ...form, subtotal, tax, total_amount: total, total_cost: cost, expected_profit: profit, margin_rate: profit / total * 100, margin_warning: profit / total < .15, valid_until: '2026-08-16', delivery_date: '2026-08-30', disclaimer: '演示系统生成，仅用于社会实践成果展示。' } }
  useEffect(() => { const timer = setTimeout(async () => { const fallback = localCalculate(); const response = await safePost('/quotes/calculate', form, fallback); setResult(response.data) }, 180); return () => clearTimeout(timer) }, [form])
  const update = (key: string, value: string) => setForm(existing => ({ ...existing, [key]: key === 'incoterm' ? value : Number(value) }))
  const save = async () => { const response = await safePost('/quotes', form, { ...result, id: Date.now(), quote_no: `QT-DEMO-${String(Date.now()).slice(-4)}` }); setSaved(response.data) }
  const download = async () => { setDownloading(true); try { const response = await client.post('/quotes/preview/pdf', form, { responseType: 'blob' }); const url = URL.createObjectURL(response.data); const a = document.createElement('a'); a.href = url; a.download = 'Yiwu-AI-Demo-Quotation.pdf'; a.click(); URL.revokeObjectURL(url) } catch { window.print() } finally { setDownloading(false) } }
  return <div>
    <PageHeader eyebrow="AI QUOTATION" title="AI自动报价中心" description="从询盘到中英文报价单，实时守住利润底线。" actions={<button className="btn btn-secondary">历史报价</button>} />
    <div className="quote-layout"><Card className="quote-form" title="报价参数"><label>选择产品<select value={form.product_id} onChange={e => { const id = Number(e.target.value); const p = fallbackProducts.find(item => item.id === id)!; setForm(old => ({ ...old, product_id: id, unit_price: p.price, unit_cost: p.cost })) }}>{fallbackProducts.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><div className="form-row"><label>数量<input type="number" value={form.quantity} onChange={e => update('quantity', e.target.value)} /></label><label>产品单价 (USD)<input type="number" step="0.1" value={form.unit_price} onChange={e => update('unit_price', e.target.value)} /></label></div><div className="form-row"><label>折扣 (%)<input type="range" min="0" max="20" value={form.discount} onChange={e => update('discount', e.target.value)} /><b>{form.discount}%</b></label><label>贸易术语<select value={form.incoterm} onChange={e => update('incoterm', e.target.value)}><option>EXW</option><option>FOB</option><option>CIF</option></select></label></div><div className="form-row"><label>包装费<input type="number" value={form.packaging_fee} onChange={e => update('packaging_fee', e.target.value)} /></label><label>运费<input type="number" value={form.freight} onChange={e => update('freight', e.target.value)} /></label></div><div className="form-row"><label>保险费<input type="number" value={form.insurance} onChange={e => update('insurance', e.target.value)} /></label><label>税费模拟比例 (%)<input type="number" value={form.tax_rate} onChange={e => update('tax_rate', e.target.value)} /></label></div><DemoNotice>税费、运费和交期均为模拟值，可现场调整。</DemoNotice></Card>
      <Card className="quote-preview" title={<><FileDown size={18} />报价单实时预览</>} action={<Badge tone="blue">CN / EN</Badge>}><div className="quote-paper"><div className="quote-brand"><div className="brand-mark">义</div><div><strong>YIWU AI TRADE COPILOT</strong><span>Smart Global Trading Quotation</span></div><span>DRAFT</span></div><div className="quote-meta"><div><small>报价编号</small><b>{saved?.quote_no || 'QT-PREVIEW'}</b></div><div><small>报价日期</small><b>2026-08-02</b></div><div><small>有效期至</small><b>{result?.valid_until || '—'}</b></div></div><div className="quote-product"><ProductVisual variant={product.id - 1} compact /><div><strong>{product.name}</strong><span>{product.sku}</span><small>{form.quantity.toLocaleString()} PCS · {form.incoterm} NINGBO</small></div><b>${form.unit_price.toFixed(2)}</b></div>{result && <div className="quote-totals"><span>产品小计 <b>${result.subtotal.toLocaleString(undefined, { maximumFractionDigits: 2 })}</b></span><span>折扣 <b>-{form.discount}%</b></span><span>包装费 <b>${form.packaging_fee.toLocaleString()}</b></span><span>运费 + 保险 <b>${(form.freight + form.insurance).toLocaleString()}</b></span><span>税费模拟 <b>${result.tax.toLocaleString(undefined, { maximumFractionDigits: 2 })}</b></span><strong>报价总额 <b>USD {result.total_amount.toLocaleString(undefined, { maximumFractionDigits: 2 })}</b></strong></div>}<div className="quote-note">预计交货：{result?.delivery_date || '—'} · 付款建议：30%预付款，70%发货前付清</div><p className="paper-disclaimer">演示系统生成，仅用于社会实践成果展示 / For educational demo only.</p></div></Card>
      <aside className="quote-insights"><Card title="利润护栏">{result && <><div className={`margin-score ${result.margin_warning ? 'warning' : ''}`}><span>预计毛利率</span><strong>{result.margin_rate.toFixed(1)}%</strong><small>{result.margin_warning ? '低于15%警戒线' : '利润空间健康'}</small></div><div className="detail-list"><span>总成本 <b>${result.total_cost.toLocaleString()}</b></span><span>预计利润 <b>${result.expected_profit.toLocaleString()}</b></span><span>有效期 <b>14天</b></span><span>交货周期 <b>28天</b></span></div></>}</Card><button className="btn btn-primary btn-block" onClick={save}><Check size={16} />{saved ? `已保存 ${saved.quote_no}` : '保存历史报价'}</button><button className="btn btn-secondary btn-block" onClick={download}><Download size={16} />{downloading ? '正在生成PDF…' : '下载中英文PDF'}</button><button className="btn btn-ghost btn-block"><Send size={16} />发送给采购商</button></aside></div>
  </div>
}
