'use client'
import { useMutation, useQuery } from '@tanstack/react-query'
import { Bot, CheckCircle2, Database, Plus, Send, ShieldCheck, Sparkles, UserRound } from 'lucide-react'
import { useState } from 'react'
import { api } from '@/lib/api'
import type { AgentResponse, Customer, Paginated } from '@/lib/types'
import { PageHeader } from '@/components/page-header'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Select, Textarea } from '@/components/ui/input'

type Message={role:'user'|'assistant';content:string;response?:AgentResponse}
export function AgentPage(){const [customerId,setCustomerId]=useState('5');const [input,setInput]=useState('为什么这个客户最近被评为高风险？');const [messages,setMessages]=useState<Message[]>([{role:'assistant',content:'你好，我是 TradeGuard 风控 Agent。我只能通过受控工具查询事实，并会在右侧展示数据来源与证据。'}]);const [last,setLast]=useState<AgentResponse|null>(null);const customers=useQuery({queryKey:['agent-customers'],queryFn:()=>api<Paginated<Customer>>('/api/customers?page_size=100')});const chat=useMutation({mutationFn:(message:string)=>api<AgentResponse>('/api/agent/chat',{method:'POST',body:JSON.stringify({message,customer_id:customerId?Number(customerId):null,conversation_id:'roadshow-main'})}),onSuccess:(response,message)=>{setMessages(current=>[...current,{role:'user',content:message},{role:'assistant',content:response.answer,response}]);setLast(response)},onError:(error,message)=>setMessages(current=>[...current,{role:'user',content:message},{role:'assistant',content:`请求失败：${error.message}` }])});const send=()=>{const message=input.trim();if(!message||chat.isPending)return;setInput('');chat.mutate(message)};return <div><PageHeader eyebrow="EVIDENCE-BASED AGENT" title="AI 风控 Agent" description="Agent 负责查询、比较和解释，不直接访问数据库；右侧面板公开每次工具调用、数据来源和关联实体。" actions={<Badge tone="success">MOCK MODE · 无需 API Key</Badge>}/>
  <div className="grid min-h-[690px] gap-4 xl:grid-cols-[230px_1fr_320px]"><Card className="overflow-hidden"><div className="border-b border-slate-100 p-4"><Button className="w-full" size="sm"><Plus size={14}/>新建会话</Button></div><div className="p-3"><p className="px-2 pb-2 text-[9px] font-bold tracking-wider text-slate-400">历史会话</p>{['高风险客户解释','对比客户 5 和 7','生成企业核验清单'].map((item,index)=><button key={item} className={`mb-1 w-full rounded-lg p-3 text-left ${index===0?'bg-teal-50':'hover:bg-slate-50'}`}><strong className="block text-[11px]">{item}</strong><span className="mt-1 block text-[8px] text-slate-400">roadshow-{index+1}</span></button>)}</div><div className="mx-3 mt-auto rounded-lg bg-slate-50 p-3 text-[9px] leading-5 text-slate-500"><ShieldCheck size={15} className="mb-2 text-teal-600"/>Agent 不会执行 SQL，也不会自动暂停发货或加入黑名单。</div></Card>
    <Card className="flex min-h-[690px] flex-col overflow-hidden"><div className="flex items-center gap-3 border-b border-slate-100 p-4"><div className="grid size-9 place-items-center rounded-lg bg-teal-100 text-teal-700"><Bot size={19}/></div><div><strong className="block text-xs">TradeGuard Agent</strong><span className="text-[9px] text-slate-400">工具调用 · 事实约束 · 模板降级</span></div><Select className="ml-auto w-48" value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">不指定外商</option>{customers.data?.items.map(c=><option value={c.id} key={c.id}>#{c.id} {c.company_name}</option>)}</Select></div><div className="flex-1 space-y-4 overflow-auto bg-slate-50/60 p-5">{messages.map((message,index)=><div key={index} className={`flex gap-2 ${message.role==='user'?'justify-end':''}`}>{message.role==='assistant'&&<span className="grid size-7 shrink-0 place-items-center rounded-lg bg-teal-600 text-white"><Bot size={14}/></span>}<div className={`max-w-[78%] rounded-xl px-4 py-3 text-xs leading-6 whitespace-pre-wrap ${message.role==='user'?'bg-[#0b3b37] text-white':'border border-slate-200 bg-white text-slate-700'}`}>{message.content}{message.response&&<div className="mt-2 flex gap-1 border-t border-slate-100 pt-2"><Badge tone="success">{message.response.mode}</Badge><Badge>{message.response.tools_called.length} 个工具</Badge></div>}</div>{message.role==='user'&&<span className="grid size-7 shrink-0 place-items-center rounded-lg bg-slate-200 text-slate-600"><UserRound size={14}/></span>}</div>)}{chat.isPending&&<div className="flex items-center gap-2 text-xs text-slate-400"><Sparkles size={14} className="animate-pulse"/>正在路由工具并组织证据…</div>}</div><div className="border-t border-slate-100 p-4"><Textarea rows={3} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="询问信用分、交易历史、风险原因或输入“比较客户 5 和 7”"/><div className="mt-2 flex items-center justify-between"><span className="text-[8px] text-slate-400">Enter 发送 · Shift+Enter 换行</span><Button size="sm" onClick={send} disabled={!input.trim()||chat.isPending}><Send size={14}/>发送</Button></div></div></Card>
    <Card className="overflow-hidden"><div className="border-b border-slate-100 p-4"><div className="flex items-center gap-2"><Database size={16} className="text-teal-600"/><strong className="text-xs">工具调用与证据</strong></div><p className="mt-1 text-[9px] text-slate-400">公开 Agent 使用的每条事实来源</p></div>{last?<div className="max-h-[630px] overflow-auto p-4"><p className="text-[9px] font-bold text-slate-400">TOOLS CALLED</p><div className="mt-2 space-y-2">{last.tools_called.map((call,index)=><div key={`${call.tool}-${index}`} className="rounded-lg border border-slate-200 p-3"><div className="flex items-center gap-2"><CheckCircle2 size={13} className="text-teal-600"/><strong className="text-[10px]">{call.tool}</strong></div><p className="mt-1 text-[9px] text-slate-500">{call.summary}</p><pre className="mt-2 overflow-auto rounded bg-slate-950 p-2 text-[8px] text-teal-200">{JSON.stringify(call.arguments,null,2)}</pre></div>)}</div><p className="mt-5 text-[9px] font-bold text-slate-400">DATA SOURCES</p><div className="mt-2 flex flex-wrap gap-1">{last.data_sources.map(source=><Badge key={source}>{source}</Badge>)}</div><p className="mt-5 text-[9px] font-bold text-slate-400">RELATED ENTITIES</p><div className="mt-2 space-y-1 text-[9px] text-slate-600"><p>客户：{last.related_customer_ids.join(', ')||'无'}</p><p>订单：{last.related_order_ids.join(', ')||'无'}</p><p>风险事件：{last.related_risk_event_ids.join(', ')||'无'}</p></div><p className="mt-5 rounded-lg bg-amber-50 p-3 text-[9px] leading-5 text-amber-800">{last.disclaimer}</p></div>:<div className="grid min-h-96 place-items-center px-6 text-center text-[10px] leading-5 text-slate-400"><div><Database className="mx-auto mb-3"/><p>发送问题后，这里会显示工具调用、查询客户、订单与风险事件。</p></div></div>}</Card></div>
</div>}
