'use client'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CheckCircle2, Clock3, FileWarning, ShieldCheck } from 'lucide-react'
import { useState } from 'react'
import { toast } from 'sonner'
import { api } from '@/lib/api'
import type { Paginated, RiskEvent } from '@/lib/types'
import { dateTime } from '@/lib/utils'
import { PageHeader } from '@/components/page-header'
import { Badge, riskLabel } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader } from '@/components/ui/card'
import { Select, Textarea } from '@/components/ui/input'
import { ErrorState, Loading } from '@/components/states'

export function AlertsPage(){const qc=useQueryClient();const [risk,setRisk]=useState('');const [status,setStatus]=useState('');const [selectedState,setSelected]=useState<RiskEvent|null>(null);const [nextStatus,setNextStatus]=useState('investigating');const [action,setAction]=useState('review');const [resolution,setResolution]=useState('');const [confirmed,setConfirmed]=useState(false);const query=useQuery({queryKey:['alerts',risk,status],queryFn:()=>api<Paginated<RiskEvent>>(`/api/risk/alerts?page_size=100&risk_level=${risk}&status=${status}`)});const selected=selectedState??query.data?.items[0]??null;const update=useMutation({mutationFn:()=>api<RiskEvent>(`/api/risk/alerts/${selected?.id}/status`,{method:'PUT',body:JSON.stringify({status:nextStatus,resolution,assigned_to:'路演审核员',action,confirmed})}),onSuccess:data=>{toast.success('处置状态和审计日志已更新');setSelected(data);qc.invalidateQueries({queryKey:['alerts']})},onError:e=>toast.error(e.message)});return <div><PageHeader eyebrow="ALERT RESPONSE CENTER" title="风险预警中心" description="查看规则证据、模型特征和处置建议；确认风险、误报、观察名单等操作都会写入审计日志。"/>
  <div className="mb-4 flex flex-col gap-3 sm:flex-row"><Select className="sm:w-44" value={risk} onChange={e=>{setRisk(e.target.value);setSelected(null)}}><option value="">全部风险等级</option><option value="critical">严重风险</option><option value="high">高风险</option><option value="medium">中风险</option><option value="low">低风险</option></Select><Select className="sm:w-44" value={status} onChange={e=>{setStatus(e.target.value);setSelected(null)}}><option value="">全部状态</option>{['pending','investigating','confirmed','false_positive','resolved','closed'].map(item=><option value={item} key={item}>{item}</option>)}</Select><span className="self-center text-xs text-slate-400">{query.data?.total||0} 条预警</span></div>
  {query.isLoading?<Loading/>:query.error?<ErrorState message={query.error.message}/>:<div className="grid gap-4 xl:grid-cols-[.85fr_1.15fr]"><Card className="overflow-hidden"><div className="max-h-[720px] divide-y divide-slate-100 overflow-auto">{query.data?.items.map(event=><button key={event.id} onClick={()=>{setSelected(event);setResolution(event.resolution||'');setNextStatus(event.status==='pending'?'investigating':event.status)}} className={`w-full p-4 text-left hover:bg-slate-50 ${selected?.id===event.id?'bg-teal-50/70':''}`}><div className="flex items-center justify-between"><Badge tone={event.risk_level}>{riskLabel(event.risk_level)}</Badge><strong className="text-sm">{event.risk_score.toFixed(0)}</strong></div><h3 className="mt-2 text-xs font-bold">{event.title}</h3><p className="mt-1 line-clamp-2 text-[10px] leading-4 text-slate-400">{event.description}</p><div className="mt-2 flex items-center justify-between text-[9px] text-slate-400"><span className="flex items-center gap-1"><Clock3 size={11}/>{dateTime(event.created_at)}</span><span>{event.status}</span></div></button>)}</div></Card>
    {selected&&<div className="space-y-4"><Card><CardHeader><div><div className="flex items-center gap-2"><Badge tone={selected.risk_level}>{riskLabel(selected.risk_level)}</Badge><Badge>事件 #{selected.id}</Badge></div><h2 className="mt-3 font-bold">{selected.title}</h2></div><div className="text-right"><strong className="block text-3xl">{selected.risk_score.toFixed(0)}</strong><span className="text-[9px] text-slate-400">风险分</span></div></CardHeader><CardContent><p className="text-xs leading-6 text-slate-600">{selected.description}</p><div className="mt-4 grid grid-cols-3 gap-2"><div className="rounded-lg bg-slate-50 p-3"><span className="text-[9px] text-slate-400">外商</span><strong className="mt-1 block text-xs">#{selected.customer_id}</strong></div><div className="rounded-lg bg-slate-50 p-3"><span className="text-[9px] text-slate-400">订单</span><strong className="mt-1 block text-xs">{selected.order_id?`#${selected.order_id}`:'模拟订单'}</strong></div><div className="rounded-lg bg-slate-50 p-3"><span className="text-[9px] text-slate-400">状态</span><strong className="mt-1 block text-xs">{selected.status}</strong></div></div></CardContent></Card>
      <Card><CardHeader><h3 className="text-sm font-bold">规则证据链</h3><FileWarning size={17} className="text-orange-500"/></CardHeader><div className="divide-y divide-slate-100">{selected.triggered_rules.length?selected.triggered_rules.map(rule=><div key={rule.rule_code} className="p-4"><div className="flex items-center justify-between"><strong className="text-xs">{rule.rule_name}</strong><Badge tone={rule.risk_level}>{rule.risk_score} 分</Badge></div><p className="mt-2 text-[11px] text-slate-600">{rule.reason}</p><div className="mt-2 flex flex-wrap gap-1">{Object.entries(rule.evidence).slice(0,5).map(([key,value])=><span key={key} className="rounded bg-slate-100 px-2 py-1 text-[8px] text-slate-500">{key}: {String(value).slice(0,40)}</span>)}</div></div>):<p className="p-4 text-xs text-slate-400">该事件由异常模型或人工复核生成，没有明确规则命中。</p>}</div></Card>
      <Card><CardHeader><h3 className="text-sm font-bold">人工处置</h3><ShieldCheck size={17} className="text-teal-600"/></CardHeader><CardContent className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><label><span className="mb-1 block text-[9px] font-semibold text-slate-500">更新状态</span><Select value={nextStatus} onChange={e=>setNextStatus(e.target.value)}>{['pending','investigating','confirmed','false_positive','resolved','closed'].map(item=><option key={item}>{item}</option>)}</Select></label><label><span className="mb-1 block text-[9px] font-semibold text-slate-500">处置动作</span><Select value={action} onChange={e=>{setAction(e.target.value);setConfirmed(false)}}><option value="review">转人工审核</option><option value="request_materials">要求补充材料</option><option value="raise_deposit">提高定金比例</option><option value="watchlist">加入观察名单</option><option value="pause_shipping">暂停发货</option><option value="blacklist">加入黑名单</option><option value="close">关闭事件</option></Select></label></div><Textarea rows={3} placeholder="填写调查结果或处置备注" value={resolution} onChange={e=>setResolution(e.target.value)}/>{['pause_shipping','blacklist'].includes(action)&&<label className="flex items-start gap-2 rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} className="mt-0.5"/><span><strong className="block">确认高风险操作</strong>我理解该操作必须由授权人员人工确认，并会写入审计日志。</span></label>}<Button className="w-full" onClick={()=>update.mutate()} disabled={update.isPending||(['pause_shipping','blacklist'].includes(action)&&!confirmed)}>{update.isPending?'保存中…':<><CheckCircle2 size={15}/>保存处置结果</>}</Button></CardContent></Card></div>}
  </div>}</div>}
