'use client'
import Link from 'next/link'
import { useMutation, useQuery } from '@tanstack/react-query'
import { ArrowRight, Bot, CheckCircle2, LoaderCircle, MapPin, RefreshCw, ShieldAlert, Split, TrendingUp, WalletCards, Zap } from 'lucide-react'
import { useState } from 'react'
import { toast } from 'sonner'
import { api } from '@/lib/api'
import type { RiskAnalysis } from '@/lib/types'
import { PageHeader } from '@/components/page-header'
import { Badge, riskLabel } from '@/components/ui/badge'
import { Card, CardContent, CardHeader } from '@/components/ui/card'

type Scenario={code:string;title:string;description:string;customer_id:number}
const icons=[TrendingUp,MapPin,WalletCards,Zap,Split,RefreshCw]
export function DemoScenariosPage(){const [selected,setSelected]=useState<Scenario|null>(null);const [result,setResult]=useState<RiskAnalysis|null>(null);const scenarios=useQuery({queryKey:['scenarios'],queryFn:()=>api<Scenario[]>('/api/risk/demo-scenarios')});const run=useMutation({mutationFn:(scenario:Scenario)=>api<RiskAnalysis>(`/api/risk/demo-scenarios/${scenario.code}/run`,{method:'POST'}),onMutate:(scenario)=>{setSelected(scenario);setResult(null)},onSuccess:data=>{setResult(data);toast.success('场景已运行并生成风险证据')},onError:e=>toast.error(e.message)});return <div><PageHeader eyebrow="ROADSHOW PLAYBOOK" title="风险场景演示" description="六个固定模拟场景使用真实规则和模型接口，点击即可稳定复现风险证据，适合路演现场快速讲解。"/>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{scenarios.data?.map((scenario,index)=>{const Icon=icons[index%icons.length];const active=selected?.code===scenario.code;return <button key={scenario.code} onClick={()=>run.mutate(scenario)} className={`rounded-xl border bg-white p-5 text-left shadow-sm hover:-translate-y-0.5 hover:shadow-lg ${active?'border-teal-500 ring-2 ring-teal-500/10':'border-slate-200'}`}><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-xl bg-teal-50 text-teal-700"><Icon size={20}/></span><span className="text-[9px] font-bold text-slate-300">0{index+1}</span></div><h3 className="mt-4 text-sm font-bold">{scenario.title}</h3><p className="mt-2 text-[10px] leading-5 text-slate-400">{scenario.description}</p><div className="mt-4 flex items-center justify-between"><Badge>客户 #{scenario.customer_id}</Badge><span className="flex items-center gap-1 text-[10px] font-semibold text-teal-600">运行场景<ArrowRight size={13}/></span></div></button>})}</div>
  <Card className="mt-5 min-h-64">{run.isPending?<div className="grid min-h-64 place-items-center"><div className="text-center"><LoaderCircle className="mx-auto animate-spin text-teal-600"/><p className="mt-3 text-xs text-slate-400">正在生成订单、执行规则与异常检测…</p></div></div>:result&&selected?<><CardHeader><div><div className="flex items-center gap-2"><Badge tone={result.risk_level}>{riskLabel(result.risk_level)}</Badge><Badge>场景：{selected.title}</Badge></div><h2 className="mt-3 text-lg font-bold">风险得分 {result.overall_risk_score.toFixed(1)} · 命中 {result.triggered_rules.length} 条规则</h2></div><Link href="/agent" className="inline-flex items-center gap-2 text-xs font-semibold text-teal-600"><Bot size={15}/>去 Agent 询问原因</Link></CardHeader><CardContent><div className="grid gap-4 lg:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><span className="text-[9px] font-bold text-slate-400">主要风险原因</span>{result.main_reasons.map(reason=><p key={reason} className="mt-2 flex gap-2 text-xs leading-5"><ShieldAlert size={14} className="mt-0.5 shrink-0 text-orange-600"/>{reason}</p>)}</div><div className="rounded-xl bg-slate-50 p-4"><span className="text-[9px] font-bold text-slate-400">触发规则</span>{result.triggered_rules.map(rule=><p key={rule.rule_code} className="mt-2 flex items-center justify-between text-xs"><span>{rule.rule_name}</span><strong>{rule.risk_score}</strong></p>)}</div><div className="rounded-xl bg-slate-50 p-4"><span className="text-[9px] font-bold text-slate-400">建议措施</span>{result.recommendations.slice(0,4).map(item=><p key={item} className="mt-2 flex gap-2 text-xs leading-5"><CheckCircle2 size={14} className="mt-0.5 shrink-0 text-teal-600"/>{item}</p>)}</div></div></CardContent></>:<div className="grid min-h-64 place-items-center text-center"><div><ShieldAlert className="mx-auto text-slate-300" size={34}/><p className="mt-3 text-xs text-slate-400">选择任一场景，结果会在此处展开。</p></div></div>}</Card>
</div>}
