'use client'
import { useMutation, useQuery } from '@tanstack/react-query'
import { AlertOctagon, ArrowRight, BrainCircuit, CheckCircle2, CircleGauge, Database, ShieldCheck, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { toast } from 'sonner'
import { api } from '@/lib/api'
import type { Customer, Paginated, RiskAnalysis } from '@/lib/types'
import { PageHeader } from '@/components/page-header'
import { Badge, riskLabel } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader } from '@/components/ui/card'
import { Input, Select } from '@/components/ui/input'

const initial={customer_id:'5',amount:'60000',product_category:'家居用品',product_name:'大额定制家居套装',payment_method:'T/T 30/70',deposit_ratio:'0.3',shipping_country:'Brazil',shipping_address:'New Distribution Center, Sao Paulo'}
const pipeline=[
  {number:'1',Icon:Database,label:'读取历史事实'},
  {number:'2',Icon:ShieldCheck,label:'运行规则引擎'},
  {number:'3',Icon:BrainCircuit,label:'异常模型推理'},
  {number:'4',Icon:CircleGauge,label:'融合风险得分'},
  {number:'5',Icon:Sparkles,label:'生成核验建议'},
]
export function RiskCheckPage(){const [form,setForm]=useState(initial);const [result,setResult]=useState<RiskAnalysis|null>(null);const customers=useQuery({queryKey:['risk-customers'],queryFn:()=>api<Paginated<Customer>>('/api/customers?page_size=100')});const analyze=useMutation({mutationFn:()=>api<RiskAnalysis>('/api/risk/analyze-order',{method:'POST',body:JSON.stringify({...form,customer_id:Number(form.customer_id),amount:Number(form.amount),deposit_ratio:Number(form.deposit_ratio),order_time:new Date().toISOString(),persist_event:true})}),onSuccess:data=>{setResult(data);toast.success('风险检测完成，证据已生成')},onError:e=>toast.error(e.message)});const color=result?.risk_level==='critical'?'#dc2626':result?.risk_level==='high'?'#ea580c':result?.risk_level==='medium'?'#d97706':'#0d9488';return <div><PageHeader eyebrow="REAL-TIME RISK CHECK" title="新订单风险检测" description="输入一笔待确认订单，系统依次读取客户信用、运行 12 条规则、提取统计特征并调用 Isolation Forest，最后生成可追溯证据。"/>
  <div className="mb-4 grid grid-cols-2 gap-2 text-[10px] sm:grid-cols-5">{pipeline.map(({number,Icon,label})=><div key={number} className="flex items-center gap-2 rounded-lg border border-slate-200 bg-white p-3"><span className="grid size-6 place-items-center rounded-full bg-teal-50 font-bold text-teal-700">{number}</span><Icon size={14} className="text-teal-600"/><span>{label}</span></div>)}</div>
  <div className="grid gap-4 xl:grid-cols-[.75fr_1.25fr]"><Card><CardHeader><div><h2 className="text-sm font-bold">待检测订单</h2><p className="mt-1 text-[10px] text-slate-400">不会自动暂停发货或加入黑名单</p></div></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 xl:grid-cols-1 2xl:grid-cols-2">{[['customer_id','外商'],['amount','订单金额 USD'],['product_category','商品品类'],['product_name','商品名称'],['payment_method','付款方式'],['deposit_ratio','定金比例'],['shipping_country','收货国家'],['shipping_address','收货地址']].map(([key,label])=><label key={key} className={key==='shipping_address'?'sm:col-span-2 xl:col-span-1 2xl:col-span-2':''}><span className="mb-1.5 block text-[10px] font-semibold text-slate-500">{label}</span>{key==='customer_id'?<Select value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})}>{customers.data?.items.map(c=><option value={c.id} key={c.id}>#{c.id} {c.company_name}</option>)}</Select>:key==='payment_method'?<Select value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}>{['T/T 30/70','T/T 50/50','Letter of Credit','Open Account 90 days','Cash on Delivery'].map(i=><option key={i}>{i}</option>)}</Select>:<Input type={['amount','deposit_ratio'].includes(key)?'number':'text'} step={key==='deposit_ratio'?'.1':undefined} value={form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>)}<Button className="mt-1 sm:col-span-2 xl:col-span-1 2xl:col-span-2" onClick={()=>analyze.mutate()} disabled={analyze.isPending}>{analyze.isPending?'正在运行规则与模型…':<>立即检测<ArrowRight size={15}/></>}</Button></CardContent></Card>
    {!result?<Card className="grid min-h-[580px] place-items-center border-dashed"><div className="max-w-sm text-center"><div className="mx-auto grid size-16 place-items-center rounded-2xl bg-teal-50 text-teal-600"><ShieldCheck size={30}/></div><h3 className="mt-5 font-bold">等待检测订单</h3><p className="mt-2 text-xs leading-6 text-slate-400">结果区将展示总体风险分、信用分、异常度、规则证据和确定性处置建议。</p></div></Card>:<div className="space-y-4"><Card className="overflow-hidden"><div className="flex flex-col gap-5 p-6 sm:flex-row sm:items-center"><div className="score-ring size-32" style={{'--score':result.overall_risk_score,'--ring-color':color} as React.CSSProperties}><div className="text-center"><strong className="block text-3xl">{result.overall_risk_score.toFixed(0)}</strong><span className="text-[9px] text-slate-400">总体风险分</span></div></div><div className="flex-1"><div className="flex items-center gap-2"><Badge tone={result.risk_level} className="text-sm">{riskLabel(result.risk_level)}</Badge><span className="text-[10px] text-slate-400">事件 #{result.risk_event_id||'未落库'}</span></div><h2 className="mt-3 text-xl font-bold">{result.risk_level==='critical'?'建议暂停并转人工增强审核':result.risk_level==='high'?'建议转人工审核并提高交易保障':'建议补充核验后继续'}</h2><div className="mt-4 grid grid-cols-3 gap-2"><div className="rounded-lg bg-slate-50 p-3"><span className="text-[9px] text-slate-400">客户信用</span><strong className="mt-1 block">{result.credit_score.toFixed(1)}</strong><small className="text-[8px] text-slate-400">{result.credit_confidence}</small></div><div className="rounded-lg bg-slate-50 p-3"><span className="text-[9px] text-slate-400">模型异常度</span><strong className="mt-1 block">{(result.anomaly_score*100).toFixed(0)}%</strong><small className="text-[8px] text-slate-400">{result.model_version}</small></div><div className="rounded-lg bg-slate-50 p-3"><span className="text-[9px] text-slate-400">触发规则</span><strong className="mt-1 block">{result.triggered_rules.length} 条</strong><small className="text-[8px] text-slate-400">{result.rule_version}</small></div></div></div></div></Card>
      <Card><CardHeader><h3 className="text-sm font-bold">触发规则与证据</h3><Badge tone="neutral">可复现规则</Badge></CardHeader><div className="divide-y divide-slate-100">{result.triggered_rules.length?result.triggered_rules.map(rule=><div key={rule.rule_code} className="p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><AlertOctagon size={15} className="text-orange-600"/><strong className="text-xs">{rule.rule_name}</strong></div><Badge tone={rule.risk_level}>{rule.risk_score.toFixed(0)} 分</Badge></div><p className="mt-2 text-xs text-slate-600">{rule.reason}</p><pre className="mt-2 overflow-auto rounded-lg bg-slate-950 p-3 text-[9px] leading-5 text-teal-200">{JSON.stringify(rule.evidence,null,2)}</pre></div>):<p className="p-5 text-xs text-slate-400">没有触发明确规则，综合分主要来自信用与异常模型。</p>}</div></Card>
      <Card><CardHeader><h3 className="text-sm font-bold">建议措施</h3><span className="text-[9px] text-red-500">需人工确认</span></CardHeader><CardContent className="space-y-2">{result.recommendations.map(item=><p key={item} className="flex gap-2 text-xs leading-5"><CheckCircle2 size={15} className="mt-0.5 shrink-0 text-teal-600"/>{item}</p>)}<p className="mt-4 rounded-lg bg-amber-50 p-3 text-[10px] leading-5 text-amber-800">{result.disclaimer}</p></CardContent></Card></div>}
  </div></div>}
