'use client'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { FileUp, Plus, Search, X } from 'lucide-react'
import { useRef, useState } from 'react'
import { toast } from 'sonner'
import { api, upload } from '@/lib/api'
import type { Customer, Paginated, Transaction } from '@/lib/types'
import { money } from '@/lib/utils'
import { PageHeader } from '@/components/page-header'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { Input, Select } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { ErrorState, Loading } from '@/components/states'

type ImportResult={total_rows:number;success_count:number;failed_count:number;errors:{row:number;reason:string}[]}
const initial={customer_id:'',order_number:'',product_category:'家居用品',product_name:'演示商品',amount:'10000',currency:'USD',order_time:new Date().toISOString().slice(0,16),payment_method:'T/T 30/70',deposit_ratio:'0.3',shipping_country:'France',shipping_address:'Demo Address',run_risk_analysis:true}
export function TransactionsPage(){const qc=useQueryClient();const input=useRef<HTMLInputElement>(null);const [search,setSearch]=useState('');const [open,setOpen]=useState(false);const [form,setForm]=useState(initial);const transactions=useQuery({queryKey:['transactions',search],queryFn:()=>api<Paginated<Transaction>>(`/api/transactions?search=${encodeURIComponent(search)}&page_size=50`)});const customers=useQuery({queryKey:['customers-all'],queryFn:()=>api<Paginated<Customer>>('/api/customers?page_size=100')});const create=useMutation({mutationFn:()=>api('/api/transactions',{method:'POST',body:JSON.stringify({...form,customer_id:Number(form.customer_id),amount:Number(form.amount),deposit_ratio:Number(form.deposit_ratio),order_time:new Date(form.order_time).toISOString()})}),onSuccess:()=>{toast.success('交易已创建并完成风险检测');setOpen(false);setForm(initial);qc.invalidateQueries({queryKey:['transactions']})},onError:e=>toast.error(e.message)});const importFile=async(file?:File)=>{if(!file)return;try{const result=await upload<ImportResult>('/api/transactions/import',file);toast.success(`导入完成：成功 ${result.success_count}，失败 ${result.failed_count}`);if(result.errors.length)toast.warning(`首个错误：第 ${result.errors[0].row} 行 ${result.errors[0].reason}`);qc.invalidateQueries({queryKey:['transactions']})}catch(e){toast.error(e instanceof Error?e.message:'导入失败')}finally{if(input.current)input.current.value=''}};return <div><PageHeader eyebrow="TRANSACTION LEDGER" title="交易管理" description="新增订单或导入 CSV/XLSX；导入后自动重算相关外商信用分，并对最新交易运行规则和异常检测。" actions={<><input ref={input} type="file" accept=".csv,.xlsx" className="hidden" onChange={e=>importFile(e.target.files?.[0])}/><Button variant="outline" onClick={()=>input.current?.click()}><FileUp size={15}/>导入交易</Button><Button onClick={()=>setOpen(true)}><Plus size={15}/>新增交易</Button></>}/>
  <Card className="mb-4 flex items-center gap-2 p-4"><Search size={16} className="text-slate-400"/><Input className="border-0 shadow-none focus:ring-0" placeholder="搜索订单号" value={search} onChange={e=>setSearch(e.target.value)}/><a href="/sample_data/transactions_template.csv" className="whitespace-nowrap text-xs font-semibold text-teal-600">下载模板</a></Card>
  {transactions.isLoading?<Loading/>:transactions.error?<ErrorState message={transactions.error.message}/>:<Card className="overflow-hidden"><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>订单号</th><th>外商 ID</th><th>商品</th><th>金额</th><th>付款方式</th><th>收货国家</th><th>履约状态</th><th>下单时间</th></tr></thead><tbody>{transactions.data?.items.map(tx=><tr key={tx.id}><td className="font-semibold text-teal-700">{tx.order_number}</td><td>#{tx.customer_id}</td><td><strong className="block">{tx.product_name}</strong><span className="text-[9px] text-slate-400">{tx.product_category}</span></td><td className="font-semibold">{money(tx.amount,tx.currency)}</td><td>{tx.payment_method}</td><td>{tx.shipping_country}</td><td><Badge tone={tx.dispute_status!=='none'||tx.overdue_days?'high':'success'}>{tx.dispute_status!=='none'?'存在纠纷':tx.overdue_days?`逾期 ${tx.overdue_days} 天`:'正常'}</Badge></td><td>{new Date(tx.order_time).toLocaleDateString('zh-CN')}</td></tr>)}</tbody></table></div></Card>}
  {open&&<div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/45 p-4"><Card className="max-h-[92vh] w-full max-w-2xl overflow-auto"><div className="flex items-start justify-between border-b border-slate-100 p-5"><div><h2 className="font-bold">新增交易</h2><p className="mt-1 text-[10px] text-slate-400">保存后将自动更新信用评分并创建必要预警</p></div><button onClick={()=>setOpen(false)}><X size={19}/></button></div><div className="grid gap-4 p-5 sm:grid-cols-2">{[['customer_id','选择外商'],['order_number','订单号'],['product_category','商品品类'],['product_name','商品名称'],['amount','金额 USD'],['order_time','下单时间'],['payment_method','付款方式'],['deposit_ratio','定金比例'],['shipping_country','收货国家'],['shipping_address','收货地址']].map(([key,label])=><label key={key} className={key==='shipping_address'?'sm:col-span-2':''}><span className="mb-1.5 block text-[10px] font-semibold text-slate-500">{label}</span>{key==='customer_id'?<Select value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})}><option value="">请选择</option>{customers.data?.items.map(c=><option value={c.id} key={c.id}>{c.company_name}</option>)}</Select>:<Input type={['amount','deposit_ratio'].includes(key)?'number':key==='order_time'?'datetime-local':'text'} step={key==='deposit_ratio'?'.1':undefined} value={String(form[key as keyof typeof form])} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>)}</div><div className="flex justify-end gap-2 border-t border-slate-100 p-5"><Button variant="outline" onClick={()=>setOpen(false)}>取消</Button><Button onClick={()=>create.mutate()} disabled={create.isPending||!form.customer_id||!form.order_number}>{create.isPending?'保存并检测中…':'保存并运行风控'}</Button></div></Card></div>}
</div>}
